#cloud-config
#ssh_authorized_keys:
  #- ${ssh_pub_key}

mounts:
  - [ ${nfs_id}.efs.${aws_region}.amazonaws.com, /mnt/nfs, "nfs4,nfsvers=4.1", "auto", "0", "0" ]

write_files:
  # HASHICORP VAULT CONFIG AGENT
  - path: /etc/vault.d/vault.hcl
    permissions: 0755
    owner: root
    content: |
      exit_after_auth = false
      pid_file = "./pidfile"

      auto_auth {
        method "aws" {
          mount_path = "auth/aws"
          config = {
            type = "iam"
            role = "${app_role}"
          }
        }

        sink "file" {
          config = {
            #path = "/home/ubuntu/vault-token-via-agent"
            path = "./vault-token"
            mode = 644
          }
        }
      }

      vault {
        address = "https://${vault_addr}:8200"
        tls_skip_verify = true
        retry {
          num_retries = 5
        }
      }

      cache {
        use_auto_auth_token = true
      }

      listener "tcp" {
        address = "127.0.0.1:8100"
        tls_disable = true
      }

runcmd: